name = input("Enter your name:")
age =  int(input("Enter your age:"))
print(" Hello " , name , " you are " , age , " years old ")
print(f" Hello {name} you are {age} years old ")
print(f"namaste {name}")   